version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.6.0
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build next
          command: npm run next:build

      - run:
          name: Export next
          command: npm run next:export

      - save_cache:
          paths:
            - node_modules
            - dist
            - out
            - package.json
            - firebase.json
            - .firebaserc
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

  deploy_firebase:
    docker:
      - image: circleci/node:11.6.0
    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: show directory
          command: pwd
      - run:
          name: Install Firebase
          command: npm install --save-dev firebase
      - run:
          name: look in directory
          command: ls -ltr
      - run:
          name: Deploy Master to Firebase
          command: npm run firebase-deploy -- --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  ultimate_pipeline:
    jobs:
      - build
      - deploy_firebase:
          requires:
            - build
          filters:
            branches:
              only: master
